apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: apps-repo
  namespace: flux-system
spec:
  interval: 1m
  url: ssh://git@github.com/SlipaNeSpi/apps-repo
  ref:
    branch: main
  secretRef:
    name: flux-system